DROP VIEW IF EXISTS v_q_a CASCADE;
CREATE OR REPLACE VIEW v_q_screening AS

SELECT
"id"::NUMERIC as applicant_id,
sex,
age::NUMERIC,
drivexp,
licence_year::NUMERIC,
regdriving_years::NUMERIC,
km_overall::NUMERIC,
km_12month::NUMERIC,
driving_freq,
ds_01::NUMERIC as ds_01,
ds_02::NUMERIC,
ds_03::NUMERIC,
ds_04::NUMERIC,
ds_05::NUMERIC,
ds_06::NUMERIC,
ds_07::NUMERIC,
ds_08::NUMERIC,
ds_09::NUMERIC,
ds_10::NUMERIC,
ds_11::NUMERIC,
vip_01::NUMERIC,
vip_02::NUMERIC,
vip_03::NUMERIC,
vip_04::NUMERIC,
vip_05::NUMERIC,
vip_06::NUMERIC,
vip_07::NUMERIC,
vip_08::NUMERIC,
vip_09::NUMERIC,
vip_10::NUMERIC,
vip_11::NUMERIC,
vip_12::NUMERIC,
vip_13::NUMERIC,
vip_14::NUMERIC,
vip_15::NUMERIC,
vip_16::NUMERIC,
vip_17::NUMERIC,
vip_18::NUMERIC,
vip_19::NUMERIC,
vip_20::NUMERIC,
vip_21::NUMERIC,
vip_22::NUMERIC,
vip_23::NUMERIC,
vip_24::NUMERIC,
vip_25::NUMERIC,
vip_26::NUMERIC,
vip_27::NUMERIC,
vip_28::NUMERIC,
vip_29::NUMERIC,
vip_30::NUMERIC,
vip_31::NUMERIC,
vip_32::NUMERIC,
vip_33::NUMERIC,
vip_34::NUMERIC,
vip_35::NUMERIC,
vip_36::NUMERIC,
vip_37::NUMERIC,
vip_38::NUMERIC,
vip_39::NUMERIC,
vip_40::NUMERIC,
vip_41::NUMERIC,
vip_42::NUMERIC,
vip_43::NUMERIC,
vip_44::NUMERIC,
vip_45::NUMERIC,
vip_46::NUMERIC,
vip_47::NUMERIC,
vip_48::NUMERIC,
vip_49::NUMERIC,
score_us::NUMERIC,
score_ai::NUMERIC,
score_ea::NUMERIC,
score_se::NUMERIC,
pr_us_comp::NUMERIC,
pr_ai_comp::NUMERIC,
pr_ea_comp::NUMERIC,
pr_se_comp::NUMERIC,
pr_us_int::NUMERIC,
pr_ai_int::NUMERIC,
pr_ea_int::NUMERIC,
pr_se_int::NUMERIC,
"GROUP" as "group"

FROM 
"public"."150924_data4screen-export_formatiert_V7_filter_4postgreSQL"


ORDER BY
applicant_id